export default {
  cart: [],
  buyer: [],
  orders: [],
  categories: [
    {
      name: 'hogar', products: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
    },
     { name: 'cocina', products: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
    },
    {
      name: 'tegnologia', products: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
    },
    {
      name: 'saludBelleza', products: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
    },
    {
      name: 'automotriz', products: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
    },
    {
      name: 'jugueteria', products: [         
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
    },
    {
      name: 'moda', products: [  
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
    },
    {
      name: 'deporte', products: [  
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
    },
    {
      name: 'marketplace', products: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
    }
  ]
/*   categories: [
    {
      hogar: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
      cocina: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
      tegnologia: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
      saludBelleza: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
      automotriz: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
      juguetes: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
      moda: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
      deporte: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
      marketplace: [ 
        {
          id: '1',
          image: 'https://arepa.s3.amazonaws.com/camiseta.png',
          title: 'Camiseta',
          price: 25,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        
        {
          id: '3',
          image: 'https://arepa.s3.amazonaws.com/mug.png',
          title: 'Mug',
          price: 10,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '4',
          image: 'https://arepa.s3.amazonaws.com/pin.png',
          title: 'Medalla',
          price: 4,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '5',
          image: 'https://arepa.s3.amazonaws.com/stickers1.png',
          title: 'Stickers',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '6',
          image: 'https://arepa.s3.amazonaws.com/stickers2.png',
          title: 'Membrete',
          price: 2,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
        {
          id: '7',
          image: 'https://arepa.s3.amazonaws.com/hoodie.png',
          title: 'Hoodie',
          price: 35,
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        },
      ],
    }
  ] */
  /*  products: [ 
    {
      id: '1',
      image: 'https://arepa.s3.amazonaws.com/camiseta.png',
      title: 'Camiseta',
      price: 25,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '2',
      image: 'https://arepa.s3.amazonaws.com/camiseta.png',
      title: 'Camiseta',
      price: 25,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '20',
      image: 'https://arepa.s3.amazonaws.com/camiseta.png',
      title: 'Camiseta',
      price: 25,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '3',
      image: 'https://arepa.s3.amazonaws.com/mug.png',
      title: 'Mug',
      price: 10,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '4',
      image: 'https://arepa.s3.amazonaws.com/pin.png',
      title: 'Medalla',
      price: 4,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '5',
      image: 'https://arepa.s3.amazonaws.com/stickers1.png',
      title: 'Stickers',
      price: 2,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '6',
      image: 'https://arepa.s3.amazonaws.com/stickers2.png',
      title: 'Membrete',
      price: 2,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '7',
      image: 'https://arepa.s3.amazonaws.com/hoodie.png',
      title: 'Hoodie',
      price: 35,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
  ], */
};

